name: .NET Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ApiLogin/ApiLogin.sln

    - name: Build
      run: dotnet build ApiLogin/ApiLogin.sln --no-restore

    - name: Unit Tests
      run: dotnet test UseCases_Testes --no-build --verbosity normal

    - name: Unit Tests ValidarTestes
      run: dotnet test ValidarTestes_UseCase --no-build --verbosity normal
